version: '3'
services:
  mydb:
    restart: always
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '114514'
      MYSQL_DATABASE: code_paste
    container_name: mydb
    ports:
      - "3306:3306"
    tty: true
  server:
    restart: on-failure:10
    build:
      context: ./server
    container_name: server
    ports:
      - "8080:8080"
    environment:
       GIN_MODE: release
       DATABASE_HOST: mydb
       DATABASE_USER: root
       DATABASE_PASSWORD: 114514
       DATABASE_PORT: 3306
       SERVER_PORT: 8080
    tty: true
    depends_on:
      - mydb
  web:
    build:
      context: ./web
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: web
    ports:
      - "80:3000"
    tty: true
    depends_on:
      - server